baseURL = 'https://charlescliff.github.io'
languageCode = 'en-us'
title = 'Happy Hacking'
theme = 'PaperMod'
Copyright = 'Copyright © 2022'

## pygmentsStyle = "trac"
## pygmentsUseClasses = true
## pygmentsCodeFences = true
## pygmentsCodefencesGuessSyntax = true
disqusShortname = 'charlescliff'

[Params]

  mainSections = ["post","posts"]
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  ## useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  toc = true

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
 
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

# [markup]
#   [markup.asciidocExt]
#     backend = 'html5'
#     extensions = []
#     failureLevel = 'fatal'
#     noHeaderOrFooter = true
#     preserveTOC = false
#     safeMode = 'unsafe'
#     sectionNumbers = false
#     trace = false
#     verbose = false
#     workingFolderCurrent = false
#     [markup.asciidocExt.attributes]

[security]
enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
